GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "lol",
    "important": true
}

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "content": "Ensure everything still works",
    "importance": true
}

###
POST http://localhost:3001/api/notes/
Content-Type: application/json

{
    "important": true
}

### ALTER A NOTE
PUT http://localhost:3001/api/notes/692d52ff0dbcb9b0a19c982f
Content-Type: application/json

{
    "content": "VS Code REST is good in testing the backend",
    "important": true
}

### DELETE
DELETE http://localhost:3001/api/notes/692d64ff0efd618861a591e3
