GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
    "title": "Hello World 2",
    "author": "Hannibal",
    "url": "www.google.com",
    "likes": "1"
}

