GET https://phonebook-wq80.onrender.com/api/persons/

### New entry
POST https://phonebook-wq80.onrender.com/api/persons/
Content-Type: application/json

{
    "name": "Febtwenty",
    "number": "0123456-123"
}

### New entry 2
POST https://phonebook-wq80.onrender.com/api/persons/
Content-Type: application/json

{
    "name": "Febtwentytwo",
    "number": "4312-123"
}

### name missing
POST https://phonebook-wq80.onrender.com/api/persons/
Content-Type: application/json

{
    "number": "0123456-123"
}

### number missing
POST https://phonebook-wq80.onrender.com/api/persons/
Content-Type: application/json

{
    "name": "Febtwenty"
}